# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexago < Formula
  desc "Hexagonal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/hexago"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.0/hexago_0.4.0_darwin_amd64.tar.gz"
      sha256 "0489aa1c75e78faf942528989b249aa2f51fff48f370b61394e05af6988b4537"

      define_method(:install) do
        bin.install "hexago"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.0/hexago_0.4.0_darwin_arm64.tar.gz"
      sha256 "cff3a72cd392fefca9a97f7470bde554b28018d562b91a596f274c218884f7e8"

      define_method(:install) do
        bin.install "hexago"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.0/hexago_0.4.0_linux_amd64.tar.gz"
      sha256 "879edbee2575d53670b6b3339861a27e77182be4c2018401064e6a081d15b86a"
      define_method(:install) do
        bin.install "hexago"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.0/hexago_0.4.0_linux_arm64.tar.gz"
      sha256 "3c998b761517b10e4b60c669353da6a1d7e4a8382abaebb3d6e5da62ff659aa3"
      define_method(:install) do
        bin.install "hexago"
      end
    end
  end
end
