# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexago < Formula
  desc "Hexagonal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/hexago"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.1/hexago_0.4.1_darwin_amd64.tar.gz"
      sha256 "b671f18ad81050a6944ee3865688ee1a4d4e1889438337e6c2fdff2ee7a3ff58"

      define_method(:install) do
        bin.install "hexago"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.1/hexago_0.4.1_darwin_arm64.tar.gz"
      sha256 "9309fc90e125dc6689df6416a363301e92637a5a9435ea5668a718789d47e2bf"

      define_method(:install) do
        bin.install "hexago"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.1/hexago_0.4.1_linux_amd64.tar.gz"
      sha256 "b02ba7c3ffff9f375af2843e7ab72a597fe445674186c121fc981517e966e664"
      define_method(:install) do
        bin.install "hexago"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/hexago/releases/download/v0.4.1/hexago_0.4.1_linux_arm64.tar.gz"
      sha256 "7fb185d6c6cce25d0a0625d137ec792d49fd511cc5cb56010b582332de8686e0"
      define_method(:install) do
        bin.install "hexago"
      end
    end
  end
end
