# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexago" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_amd64.tar.gz"
      sha256 "d887afdc8b95ac11b6c82c860a012ac27ad460ae3c243568f16ba1ba8131034b"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_arm64.tar.gz"
      sha256 "baf1721597cd164b69c0770a0023bc144226f78c4321618532b4e0a82578d28c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_amd64.tar.gz"
      sha256 "cf32c50fb0856fdce5ba7c6d4ec36c4531c785eb1fae37603b4b12bfdd44182a"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_arm64.tar.gz"
      sha256 "cdbf247c4d08927187e2c875d3179c0cfcec9049b2f53e4746849e93f9cadc89"
    end
  end

  name "hexago"
  desc "Hexagonal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/hexago"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexago"

  # No zap stanza required

end
