# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexago" do
  name "hexago"
  desc "Hexagonal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/hexago"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexago"

  on_macos do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_amd64.tar.gz"
      sha256 "4e601bf289a9e24c83a9d5cabd03bfa2088783b5f41cc9e3c9a458b2092508c9"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_arm64.tar.gz"
      sha256 "833012dcd91f32e378a4065caa4e4dcbad81303bf82da3bdd56be5be106241f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_amd64.tar.gz"
      sha256 "95e852affbe8acd73ff46907518486efa165d41b44aad46659e8a25fa4af6d8b"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_arm64.tar.gz"
      sha256 "9c7addc70080d56f941e4fce8c8f409d92f920df6d8c0e274b351f368c606108"
    end
  end

  # No zap stanza required
end
