# This file was generated by GoReleaser. DO NOT EDIT.
cask "hexago" do
  name "hexago"
  desc "Hexagonal Architecture scaffolding tool for Go"
  homepage "https://github.com/padiazg/hexago"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hexago"

  on_macos do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_amd64.tar.gz"
      sha256 "1122d09af485fe66f8e7d0dae9b9644f2154d75fe4469df9540df3d69c4c45f5"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_darwin_arm64.tar.gz"
      sha256 "dae84ae85308bb39ffa9dd8b60eccbd717c2279b782ec4585a1b6b97ba6bcde6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_amd64.tar.gz"
      sha256 "f9c3252509e61847f6cb5a7c632dac04163d1bee5a60dea13b3da1ef6f7cb2ec"
    end
    on_arm do
      url "https://github.com/padiazg/hexago/releases/download/v#{version}/hexago_#{version}_linux_arm64.tar.gz"
      sha256 "0ac703b6d4093268c094e0443ea4da925b65358f363708c95c7815130e89772a"
    end
  end

  # No zap stanza required
end
